### ISSUE TITLE
please help me look

### ISSUE THREAD

**Issue by alastone** [code-monad/ChatGPTBot#2]
python main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPTBot-master\ChatGPTBot-master\main.py", line 12, in <module>
    from revChatGPT.revChatGPT import AsyncChatbot as Chatbot
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\revchatgpt-0.0.42.1-py3.10.egg\revChatGPT\revChatGPT.py", line 14, in <module>
ModuleNotFoundError: No module named 'OpenAIAuth'

**Comment by code-monad** [comment]
```bash
pip3 install --user --upgrade git+http://github.com/acheong08/ChatGPT
python3 -m playwright install
```
Please use the latest version.
