### ISSUE TITLE
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接

### ISSUE THREAD

**Issue by jiahaochen1015** [code-monad/ChatGPTBot#3]
我使用了代理，python版本为3.10,但是运行出现下面的错误，可以帮我一下吗
INFO     | __main__:<module>:292 - Memories:{}
2022-12-13 23:12:19,775 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\anyio-3.6.2-py3.10.egg\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\anyio-3.6.2-py3.10.egg\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1070, in create_connection
    raise exceptions[0]
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1054, in create_connection
    sock = await self._connect_sock(
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 963, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 821, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 608, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\anyio-3.6.2-py3.10.egg\anyio\_core\_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_async\socks_proxy.py", line 290, in handle_async_request
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_async\socks_proxy.py", line 225, in handle_async_request
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\backends\asyncio.py", line 107, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpcore-0.16.2-py3.10.egg\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\request\_httpxrequest.py", line 183, in do_request
    res = await self._client.request(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\httpx-0.23.1-py3.10.egg\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Desktop\ChatGPTBot-master\main.py", line 319, in <module>
    application.run_polling()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_application.py", line 685, in run_polling
    return self.__run(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_application.py", line 873, in __run
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_application.py", line 862, in __run
    loop.run_until_complete(self.initialize())
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_application.py", line 372, in initialize
    await self.bot.initialize()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_extbot.py", line 252, in initialize
    await super().initialize()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\_bot.py", line 518, in initialize
    await self.get_me()
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_extbot.py", line 1647, in get_me
    return await super().get_me(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\_bot.py", line 313, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\_bot.py", line 663, in get_me
    result = await self._post(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\_bot.py", line 395, in _post
    return await self._do_post(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\ext\_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\_bot.py", line 426, in _do_post
    return await request.post(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\request\_baserequest.py", line 167, in post
    result = await self._request_wrapper(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\request\_baserequest.py", line 290, in _request_wrapper
    raise exc
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\request\_baserequest.py", line 276, in _request_wrapper
    code, payload = await self.do_request(
  File "C:\Users\LENOVO\AppData\Roaming\Python\Python310\site-packages\python_telegram_bot-20.0a6-py3.10.egg\telegram\request\_httpxrequest.py", line 204, in do_request
    raise NetworkError(f"httpx HTTPError: {err}") from err

**Comment by code-monad** [comment]
You are not able to connect to the Telegram bot API's endpoint. Please check your network, if you can successfully post request to 
`https://api.telegram.org`
测试一下你的代理能否连接`https://api.telegram.org`。

**Comment by jiahaochen1015** [comment]
> You are not able to connect to the Telegram bot API's endpoint. Please check your network, if you can successfully post request to `https://api.telegram.org` 测试一下你的代理能否连接`https://api.telegram.org`。

可以连接`https://api.telegram.org`，但是还是报同样的错误

**Comment by code-monad** [comment]
> > You are not able to connect to the Telegram bot API's endpoint. Please check your network, if you can successfully post request to `https://api.telegram.org` 测试一下你的代理能否连接`https://api.telegram.org`。
> 
> 可以连接`https://api.telegram.org`，但是还是报同样的错误

Check your Telegram bot’s API Key, is it correct?

**Comment by jiahaochen1015** [comment]
> > > You are not able to connect to the Telegram bot API's endpoint. Please check your network, if you can successfully post request to `https://api.telegram.org` 测试一下你的代理能否连接`https://api.telegram.org`。
> > 
> > 
> > 可以连接`https://api.telegram.org`，但是还是报同样的错误
> 
> Check your Telegram bot’s API Key, is it code?

抱歉，我不太明白你的意思，我已经把config文件中的token替换为Telegram bot’s API Key，但是当我在网址上输入类似https://api.telegram.org/botMytoken/METHOD_NAME时，显示page not found，我不确定这是否是正常的

**Comment by jiahaochen1015** [comment]
是不是和我的vpn配置有关？
![1](https://user-images.githubusercontent.com/90749521/207498005-5d511196-1fcc-4251-81d9-c6b3ad17efc6.png)
我是否应该改变socks的ip和port呢？

**Comment by TDR-1000** [comment]
> 是不是 dan 我 的 vpn 置 有 关？ 我 是 否 应 该 改 变socks ip dan port 呢？ ![1](https://user-images.githubusercontent.com/90749521/207498005-5d511196-1fcc-4251-81d9-c6b3ad17efc6.png)

have you made the bot in telegram? if you haven't made a bot please make it first in Telegram @BotFather if you have made the Bot later there are instructions for getting apikey tokens.

**Comment by jiahaochen1015** [comment]
> > 是不是 dan 我 的 vpn 置 有 关？ 我 是 否 应 该 改 变socks ip dan port 呢？ ![1](https://user-images.githubusercontent.com/90749521/207498005-5d511196-1fcc-4251-81d9-c6b3ad17efc6.png)
> 
> have you made the bot in telegram? if you haven't made a bot please make it first in Telegram @Botfather if you have made the Bot later there are instructions for getting apikey tokens.

I have already got the apikey tokens, and finished the config.toml. But it didn't work

**Comment by jiahaochen1015** [comment]
当我把port换为我的vpn的port，即4780时，显示如下图
![2](https://user-images.githubusercontent.com/90749521/207541636-e37049bb-e5fc-47f5-a953-4471b68dd4b8.png)
但是它将一直停止在这个位置，无论我做什么操作

**Comment by code-monad** [comment]
> 当我把port换为我的vpn的port，即4780时，显示如下图 ![2](https://user-images.githubusercontent.com/90749521/207541636-e37049bb-e5fc-47f5-a953-4471b68dd4b8.png) 但是它将一直停止在这个位置，无论我做什么操作

当你没有连接上telegram的bot api的时候，它就会是这个情况。请检查你的网络环境与配置。
